name: "build"

on:
  pull_request:
    paths-ignore:
      - ".docs/**"
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday
  workflow_dispatch:

jobs:
  qa:
    name: "Quality assurance"
    uses: contributte/.github/.github/workflows/nette-tester-qa-v2.yml@master
    with:
      php: "8.2"

  phpstan:
    name: "Static analysis"
    uses: contributte/.github/.github/workflows/nette-tester-phpstan-v2.yml@master
    with:
      php: "8.2"

  tests:
    name: "Tests"
    uses: contributte/.github/.github/workflows/nette-tester-tests-v2.yml@master
    with:
      matrix: "[8.2, 8.3, 8.4, 8.5]"
      lowest: "8.2"

  coverage:
    name: "Coverage"
    uses: contributte/.github/.github/workflows/nette-tester-coverage-v2.yml@master
    with:
      php: "8.2"
